version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend-v2"
    schedule:
      interval: "weekly"
    groups:
      stellar-and-wallet:
        patterns:
          - "@creit.tech/*"
          - "@stellar/*"
      next-and-react:
        patterns:
          - "next"
          - "react*"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
