/**
 * Reference fixtures for Cohort and Academic-Term Scoping.
 *
 * Provides realistic reference entities for testing, fallback data, and demonstrations.
 */

import type {
  AcademicCohort,
  AcademicCourse,
  AcademicInstitution,
  AcademicRegion,
  AcademicTerm,
  ProgramScopeTarget,
  ScopingReferenceData,
} from './types';

export const mockTerms: AcademicTerm[] = [
  {
    id: 'term-2026-fall',
    name: 'Fall 2026 Semester',
    code: 'FA26',
    academicYear: '2026-2027',
    startDate: '2026-09-01T00:00:00.000Z',
    endDate: '2026-12-20T23:59:59.000Z',
    status: 'active',
    censusDate: '2026-09-15T00:00:00.000Z',
  },
  {
    id: 'term-2027-spring',
    name: 'Spring 2027 Semester',
    code: 'SP27',
    academicYear: '2026-2027',
    startDate: '2027-01-15T00:00:00.000Z',
    endDate: '2027-05-30T23:59:59.000Z',
    status: 'active',
    censusDate: '2027-02-01T00:00:00.000Z',
  },
  {
    id: 'term-2026-summer',
    name: 'Summer 2026 Intensive',
    code: 'SU26',
    academicYear: '2025-2026',
    startDate: '2026-06-01T00:00:00.000Z',
    endDate: '2026-08-15T23:59:59.000Z',
    status: 'closed',
  },
  {
    id: 'term-2027-fall',
    name: 'Fall 2027 Semester',
    code: 'FA27',
    academicYear: '2027-2028',
    startDate: '2027-09-01T00:00:00.000Z',
    endDate: '2027-12-20T23:59:59.000Z',
    status: 'inactive',
  },
];

export const mockCohorts: AcademicCohort[] = [
  {
    id: 'cohort-2026-alpha',
    name: 'Smart Contract Engineering Alpha 2026',
    code: 'SCE-26A',
    startDate: '2026-09-01T00:00:00.000Z',
    endDate: '2026-12-15T23:59:59.000Z',
    status: 'active',
    capacity: 100,
    enrolledCount: 78,
    institutionId: 'inst-chainverse-acad',
    description: 'Premier developer cohort targeting Stellar and Soroban development.',
  },
  {
    id: 'cohort-2026-beta',
    name: 'Decentralized Finance Scholars Beta 2026',
    code: 'DFS-26B',
    startDate: '2026-10-01T00:00:00.000Z',
    endDate: '2027-01-30T23:59:59.000Z',
    status: 'active',
    capacity: 60,
    enrolledCount: 52,
    institutionId: 'inst-pan-african-tech',
    description: 'Specialized DeFi protocol analytics and liquidity systems cohort.',
  },
  {
    id: 'cohort-2026-summer-bootcamp',
    name: 'Summer 2026 Web3 Onramp',
    code: 'W3O-26S',
    startDate: '2026-06-01T00:00:00.000Z',
    endDate: '2026-08-30T23:59:59.000Z',
    status: 'completed',
    capacity: 80,
    enrolledCount: 80,
    institutionId: 'inst-chainverse-acad',
  },
  {
    id: 'cohort-2027-upcoming',
    name: 'Spring 2027 Security Auditors',
    code: 'SEC-27S',
    startDate: '2027-02-01T00:00:00.000Z',
    endDate: '2027-06-01T23:59:59.000Z',
    status: 'upcoming',
    capacity: 40,
    enrolledCount: 0,
    institutionId: 'inst-chainverse-acad',
  },
];

export const mockCourses: AcademicCourse[] = [
  {
    id: 'course-bc-101',
    code: 'BC-101',
    title: 'Foundations of Distributed Ledgers',
    institutionId: 'inst-chainverse-acad',
    department: 'Computer Science',
    credits: 3,
    status: 'active',
  },
  {
    id: 'course-soroban-201',
    code: 'SOR-201',
    title: 'Rust & Soroban Smart Contract Architecture',
    institutionId: 'inst-chainverse-acad',
    department: 'Software Engineering',
    credits: 4,
    status: 'active',
  },
  {
    id: 'course-defi-301',
    code: 'DEFI-301',
    title: 'Automated Market Makers & Credit Protocols',
    institutionId: 'inst-pan-african-tech',
    department: 'Applied Economics',
    credits: 4,
    status: 'active',
  },
  {
    id: 'course-audit-401',
    code: 'AUD-401',
    title: 'Protocol Security Auditing & Verification',
    institutionId: 'inst-chainverse-acad',
    department: 'Cybersecurity',
    credits: 3,
    status: 'active',
  },
];

export const mockInstitutions: AcademicInstitution[] = [
  {
    id: 'inst-chainverse-acad',
    name: 'ChainVerse Academy of Technology',
    code: 'CV-ACAD',
    region: 'africa',
    country: 'Kenya',
    status: 'active',
    accreditationStatus: 'accredited',
  },
  {
    id: 'inst-pan-african-tech',
    name: 'Pan-African Institute of Technology',
    code: 'PA-TECH',
    region: 'africa',
    country: 'Nigeria',
    status: 'active',
    accreditationStatus: 'accredited',
  },
  {
    id: 'inst-asia-crypto-institute',
    name: 'East Asia Institute of Cryptography',
    code: 'EAIC',
    region: 'asia',
    country: 'Singapore',
    status: 'active',
    accreditationStatus: 'accredited',
  },
  {
    id: 'inst-european-blockchain-school',
    name: 'European School of Decentralized Tech',
    code: 'ESDT',
    region: 'europe',
    country: 'Germany',
    status: 'active',
    accreditationStatus: 'accredited',
  },
];

export const mockRegions: AcademicRegion[] = [
  { id: 'reg-africa', code: 'africa', name: 'Africa', status: 'active' },
  { id: 'reg-asia', code: 'asia', name: 'Asia-Pacific', status: 'active' },
  { id: 'reg-europe', code: 'europe', name: 'Europe', status: 'active' },
  { id: 'reg-north-america', code: 'north-america', name: 'North America', status: 'active' },
  { id: 'reg-south-america', code: 'south-america', name: 'Latin America', status: 'active' },
  { id: 'reg-oceania', code: 'oceania', name: 'Oceania', status: 'active' },
];

export const mockProgramScopes: ProgramScopeTarget[] = [
  {
    id: 'scope-fall-2026-engineering',
    programId: 'prog-stellar-fellows-2026',
    programName: 'Stellar Developer Fellowship 2026',
    name: 'Fall 2026 African Engineering Cohort',
    description: 'Targeted support for African engineering students in the Fall 2026 term.',
    cohortIds: ['cohort-2026-alpha'],
    termIds: ['term-2026-fall'],
    courseIds: ['course-bc-101', 'course-soroban-201'],
    institutionIds: ['inst-chainverse-acad', 'inst-pan-african-tech'],
    regions: ['africa'],
    status: 'active',
    overlapPolicy: 'allow_concurrent',
    allowNewApplications: true,
    applicationStartDate: '2026-08-01T00:00:00.000Z',
    applicationEndDate: '2026-11-30T23:59:59.000Z',
    maxApplicationsPerStudent: 1,
    createdAt: '2026-07-15T10:00:00.000Z',
    updatedAt: '2026-08-01T09:00:00.000Z',
  },
  {
    id: 'scope-spring-2027-defi',
    programId: 'prog-defi-scholars-2027',
    programName: 'Global DeFi Leaders Program',
    name: 'Spring 2027 Pan-Regional DeFi Scope',
    description: 'Full tuition sponsorship for advanced protocol engineering.',
    cohortIds: ['cohort-2026-beta', 'cohort-2027-upcoming'],
    termIds: ['term-2027-spring'],
    courseIds: ['course-defi-301'],
    institutionIds: ['inst-pan-african-tech', 'inst-asia-crypto-institute'],
    regions: ['africa', 'asia'],
    status: 'active',
    overlapPolicy: 'disallow_overlap',
    allowNewApplications: true,
    applicationStartDate: '2026-10-01T00:00:00.000Z',
    applicationEndDate: '2027-01-10T23:59:59.000Z',
    maxApplicationsPerStudent: 1,
    createdAt: '2026-08-20T12:00:00.000Z',
    updatedAt: '2026-08-20T12:00:00.000Z',
  },
  {
    id: 'scope-inactive-historical-2026',
    programId: 'prog-stellar-fellows-2026',
    programName: 'Stellar Developer Fellowship 2026',
    name: 'Summer 2026 Accelerated Scope (Closed)',
    description: 'Completed summer cohort scope. No new applications allowed.',
    cohortIds: ['cohort-2026-summer-bootcamp'],
    termIds: ['term-2026-summer'],
    courseIds: ['course-bc-101'],
    institutionIds: ['inst-chainverse-acad'],
    regions: ['africa'],
    status: 'inactive',
    overlapPolicy: 'allow_concurrent',
    allowNewApplications: false,
    applicationStartDate: '2026-05-01T00:00:00.000Z',
    applicationEndDate: '2026-05-31T23:59:59.000Z',
    createdAt: '2026-04-10T08:00:00.000Z',
    updatedAt: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'scope-archived-pilot',
    programId: 'prog-pilot-bursary-2025',
    programName: 'Legacy Pilot Bursary 2025',
    name: '2025 Pilot Cohort Scope (Archived)',
    description: 'Archived pilot grant scope for record keeping.',
    cohortIds: [],
    termIds: ['term-2026-summer'],
    courseIds: ['course-bc-101'],
    institutionIds: ['inst-european-blockchain-school'],
    regions: ['europe'],
    status: 'archived',
    overlapPolicy: 'strict_exclusive',
    allowNewApplications: false,
    createdAt: '2025-09-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const mockScopingReferenceData: ScopingReferenceData = {
  cohorts: mockCohorts,
  terms: mockTerms,
  courses: mockCourses,
  institutions: mockInstitutions,
  regions: mockRegions,
};
