/**
 * Test and Development Fixtures for Sponsor Team Membership and Invitations.
 */

import type {
  PublicSponsorProfile,
  SponsorInvitation,
  SponsorOrganization,
  SponsorTeamAuditEvent,
  SponsorTeamMember,
  SponsorVerificationAuditEvent,
} from './types';

export const mockSponsorOrg: SponsorOrganization = {
  id: 'sponsor-stellar-impact',
  name: 'Stellar Impact Foundation',
  slug: 'stellar-impact',
  contactEmail: 'contact@stellarimpact.org',
  website: 'https://stellarimpact.org',
  createdAt: '2026-01-01T00:00:00.000Z',
  tenantId: 'tenant-stellar-global',
  ownerId: 'user-elena-owner',
  legalName: 'Stellar Impact Foundation Inc.',
  legalEntityType: 'foundation',
  jurisdiction: 'US',
  foundedYear: 2021,
  verificationStatus: 'verified',
  complianceTier: 'tier2_enhanced',
  isVerified: true,
  verifiedAt: '2026-01-10T14:00:00.000Z',
  verifiedBy: 'auditor-chainverse-compliance',
  verificationNotes: 'KYB verification and IRS 501(c)(3) tax exemption credentials validated.',
  branding: {
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1200&auto=format&fit=crop',
    primaryColor: '#4f46e5',
    tagline: 'Catalyzing next-generation blockchain researchers and developers worldwide.',
    bio: 'The Stellar Impact Foundation distributes merit-based bursaries and developer grants to exceptional students in cryptography, decentralized algorithms, and distributed systems.',
    website: 'https://stellarimpact.org',
    socialLinks: {
      twitter: 'https://twitter.com/stellarimpact',
      github: 'https://github.com/stellarimpact',
      linkedin: 'https://linkedin.com/company/stellarimpact',
    },
  },
  publicEmail: 'public-grants@stellarimpact.org',
  publicWebsite: 'https://stellarimpact.org',
  publicPhone: '+1 (555) 234-5678',
  privateContacts: {
    billingContact: {
      name: 'Marcus Vance',
      email: 'marcus.vance@stellarimpact.org',
      phone: '+1 (555) 019-2834',
      billingAddress: '548 Market St, Suite 39201, San Francisco, CA 94104',
    },
    legalContact: {
      name: 'Elena Rostova',
      email: 'legal@stellarimpact.org',
      phone: '+1 (555) 019-2835',
    },
    complianceContact: {
      name: 'Devon Reed',
      email: 'compliance@stellarimpact.org',
      phone: '+1 (555) 019-2836',
    },
    taxId: 'US-EIN-84-9382910',
    registrationNumber: 'DE-CORP-9281920',
  },
  complianceDocuments: [
    {
      id: 'doc-stellar-incorp',
      sponsorId: 'sponsor-stellar-impact',
      type: 'certificate_of_incorporation',
      title: 'Delaware Certificate of Incorporation',
      fileName: 'stellar_impact_incorporation_cert.pdf',
      fileSizeBytes: 2450000,
      mimeType: 'application/pdf',
      uploadedAt: '2026-01-05T10:00:00.000Z',
      uploadedBy: 'user-elena-owner',
      status: 'approved',
      reviewedAt: '2026-01-10T13:45:00.000Z',
      reviewedBy: 'auditor-chainverse-compliance',
    },
    {
      id: 'doc-stellar-tax',
      sponsorId: 'sponsor-stellar-impact',
      type: 'tax_exemption_proof',
      title: 'IRS 501(c)(3) Determination Letter',
      fileName: 'irs_501c3_determination.pdf',
      fileSizeBytes: 1820000,
      mimeType: 'application/pdf',
      uploadedAt: '2026-01-05T10:05:00.000Z',
      uploadedBy: 'user-elena-owner',
      status: 'approved',
      reviewedAt: '2026-01-10T13:50:00.000Z',
      reviewedBy: 'auditor-chainverse-compliance',
    },
  ],
};

export const mockTeamMembers: SponsorTeamMember[] = [
  {
    id: 'mem-owner-1',
    sponsorId: 'sponsor-stellar-impact',
    userId: 'user-elena-owner',
    email: 'elena.rostova@stellarimpact.org',
    name: 'Elena Rostova',
    role: 'owner',
    status: 'active',
    joinedAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    invitedBy: 'system',
    lastActiveAt: '2026-09-27T07:30:00.000Z',
  },
  {
    id: 'mem-finance-1',
    sponsorId: 'sponsor-stellar-impact',
    userId: 'user-marcus-fin',
    email: 'marcus.vance@stellarimpact.org',
    name: 'Marcus Vance',
    role: 'finance',
    status: 'active',
    joinedAt: '2026-01-15T10:00:00.000Z',
    updatedAt: '2026-01-15T10:00:00.000Z',
    invitedBy: 'user-elena-owner',
    lastActiveAt: '2026-09-26T16:45:00.000Z',
  },
  {
    id: 'mem-prog-1',
    sponsorId: 'sponsor-stellar-impact',
    userId: 'user-priya-prog',
    email: 'priya.sharma@stellarimpact.org',
    name: 'Priya Sharma',
    role: 'program',
    status: 'active',
    joinedAt: '2026-02-01T12:00:00.000Z',
    updatedAt: '2026-03-10T09:00:00.000Z',
    invitedBy: 'user-elena-owner',
    lastActiveAt: '2026-09-27T06:15:00.000Z',
  },
  {
    id: 'mem-rev-1',
    sponsorId: 'sponsor-stellar-impact',
    userId: 'user-alex-rev',
    email: 'alex.chen@stellarimpact.org',
    name: 'Dr. Alex Chen',
    role: 'reviewer',
    status: 'active',
    joinedAt: '2026-02-15T14:30:00.000Z',
    updatedAt: '2026-02-15T14:30:00.000Z',
    invitedBy: 'user-elena-owner',
    lastActiveAt: '2026-09-25T11:20:00.000Z',
  },
  {
    id: 'mem-rep-1',
    sponsorId: 'sponsor-stellar-impact',
    userId: 'user-tariq-rep',
    email: 'tariq.almansoor@stellarimpact.org',
    name: 'Tariq Al-Mansoor',
    role: 'reporting',
    status: 'active',
    joinedAt: '2026-03-01T08:00:00.000Z',
    updatedAt: '2026-03-01T08:00:00.000Z',
    invitedBy: 'user-elena-owner',
    lastActiveAt: '2026-09-26T14:00:00.000Z',
  },
  {
    id: 'mem-suspended-1',
    sponsorId: 'sponsor-stellar-impact',
    userId: 'user-sarah-susp',
    email: 'sarah.suspended@stellarimpact.org',
    name: 'Sarah Connor',
    role: 'reviewer',
    status: 'suspended',
    joinedAt: '2026-04-01T11:00:00.000Z',
    updatedAt: '2026-08-15T10:00:00.000Z',
    invitedBy: 'user-elena-owner',
    lastActiveAt: '2026-08-14T09:00:00.000Z',
  },
  {
    id: 'mem-removed-1',
    sponsorId: 'sponsor-stellar-impact',
    userId: 'user-john-rem',
    email: 'john.doe@former-partner.org',
    name: 'John Doe',
    role: 'finance',
    status: 'removed',
    joinedAt: '2026-01-20T10:00:00.000Z',
    updatedAt: '2026-05-01T15:00:00.000Z',
    invitedBy: 'user-elena-owner',
    lastActiveAt: '2026-04-30T17:00:00.000Z',
  },
];

export const mockInvitations: SponsorInvitation[] = [
  {
    id: 'inv-pending-1',
    sponsorId: 'sponsor-stellar-impact',
    sponsorName: 'Stellar Impact Foundation',
    email: 'jordan.lee@finpartners.com',
    role: 'finance',
    invitedBy: 'user-elena-owner',
    invitedByName: 'Elena Rostova',
    invitedAt: '2026-09-25T10:00:00.000Z',
    expiresAt: '2026-10-02T10:00:00.000Z',
    status: 'pending',
    token: 'inv_tok_valid_pending_1234567890abcdef',
    note: 'Overseeing Q4 disbursement batches and escrow funding.',
  },
  {
    id: 'inv-pending-2',
    sponsorId: 'sponsor-stellar-impact',
    sponsorName: 'Stellar Impact Foundation',
    email: 'dara.okonkwo@africanacad.edu',
    role: 'reviewer',
    invitedBy: 'user-elena-owner',
    invitedByName: 'Elena Rostova',
    invitedAt: '2026-09-26T14:30:00.000Z',
    expiresAt: '2026-10-03T14:30:00.000Z',
    status: 'pending',
    token: 'inv_tok_valid_pending_reviewer_234567',
    note: 'Invited to evaluate engineering applicants in cohort Alpha 2026.',
  },
  {
    id: 'inv-expired-1',
    sponsorId: 'sponsor-stellar-impact',
    sponsorName: 'Stellar Impact Foundation',
    email: 'sam.taylor@legacyreviewers.org',
    role: 'reviewer',
    invitedBy: 'user-elena-owner',
    invitedByName: 'Elena Rostova',
    invitedAt: '2026-08-01T10:00:00.000Z',
    expiresAt: '2026-08-08T10:00:00.000Z',
    status: 'expired',
    token: 'inv_tok_expired_past_due_abcdef1234',
    note: 'Fall cycle reviewer pool invitation.',
  },
  {
    id: 'inv-consumed-1',
    sponsorId: 'sponsor-stellar-impact',
    sponsorName: 'Stellar Impact Foundation',
    email: 'priya.sharma@stellarimpact.org',
    role: 'program',
    invitedBy: 'user-elena-owner',
    invitedByName: 'Elena Rostova',
    invitedAt: '2026-01-25T09:00:00.000Z',
    expiresAt: '2026-02-01T09:00:00.000Z',
    status: 'accepted',
    token: 'inv_tok_consumed_already_used_789012',
    consumedAt: '2026-02-01T12:00:00.000Z',
    note: 'Leading the Web3 STEM bursary program.',
  },
  {
    id: 'inv-revoked-1',
    sponsorId: 'sponsor-stellar-impact',
    sponsorName: 'Stellar Impact Foundation',
    email: 'malicious.actor@untrusted.xyz',
    role: 'finance',
    invitedBy: 'user-elena-owner',
    invitedByName: 'Elena Rostova',
    invitedAt: '2026-07-01T09:00:00.000Z',
    expiresAt: '2026-07-08T09:00:00.000Z',
    status: 'revoked',
    token: 'inv_tok_revoked_by_owner_456789',
    revokedAt: '2026-07-02T10:15:00.000Z',
    note: 'Wrong email address was entered; revoked immediately.',
  },
];

export const mockAuditEvents: SponsorTeamAuditEvent[] = [
  {
    id: 'aud-event-1',
    sequence: 1,
    sponsorId: 'sponsor-stellar-impact',
    actorId: 'user-elena-owner',
    actorEmail: 'elena.rostova@stellarimpact.org',
    action: 'team.invitation_created',
    targetId: 'inv-pending-1',
    targetEmail: 'jordan.lee@finpartners.com',
    newRole: 'finance',
    occurredAt: '2026-09-25T10:00:00.000Z',
    reason: 'Overseeing Q4 disbursement batches and escrow funding.',
  },
  {
    id: 'aud-event-2',
    sequence: 2,
    sponsorId: 'sponsor-stellar-impact',
    actorId: 'user-elena-owner',
    actorEmail: 'elena.rostova@stellarimpact.org',
    action: 'team.invitation_created',
    targetId: 'inv-pending-2',
    targetEmail: 'dara.okonkwo@africanacad.edu',
    newRole: 'reviewer',
    occurredAt: '2026-09-26T14:30:00.000Z',
    reason: 'Invited to evaluate engineering applicants in cohort Alpha 2026.',
  },
  {
    id: 'aud-event-3',
    sequence: 3,
    sponsorId: 'sponsor-stellar-impact',
    actorId: 'user-elena-owner',
    actorEmail: 'elena.rostova@stellarimpact.org',
    action: 'team.member_role_updated',
    targetId: 'mem-prog-1',
    targetEmail: 'priya.sharma@stellarimpact.org',
    previousRole: 'reviewer',
    newRole: 'program',
    occurredAt: '2026-03-10T09:00:00.000Z',
    reason: 'Promoted from reviewer to full program manager for Web3 STEM round.',
  },
  {
    id: 'aud-event-4',
    sequence: 4,
    sponsorId: 'sponsor-stellar-impact',
    actorId: 'user-elena-owner',
    actorEmail: 'elena.rostova@stellarimpact.org',
    action: 'team.member_removed',
    targetId: 'mem-removed-1',
    targetEmail: 'john.doe@former-partner.org',
    previousRole: 'finance',
    occurredAt: '2026-05-01T15:00:00.000Z',
    reason: 'Contract concluded; all access immediately revoked.',
  },
  {
    id: 'aud-event-5',
    sequence: 5,
    sponsorId: 'sponsor-stellar-impact',
    actorId: 'user-elena-owner',
    actorEmail: 'elena.rostova@stellarimpact.org',
    action: 'team.invitation_revoked',
    targetId: 'inv-revoked-1',
    targetEmail: 'malicious.actor@untrusted.xyz',
    occurredAt: '2026-07-02T10:15:00.000Z',
    reason: 'Wrong email address entered; revoked prior to acceptance.',
  },
];

export const mockUnverifiedSponsorOrg: SponsorOrganization = {
  id: 'sponsor-quantum-leap',
  name: 'Quantum Leap DAO',
  slug: 'quantum-leap',
  contactEmail: 'contact@quantumleapdao.xyz',
  website: 'https://quantumleapdao.xyz',
  createdAt: '2026-08-01T12:00:00.000Z',
  tenantId: 'tenant-quantum-dao',
  ownerId: 'user-satoshi-lead',
  legalName: 'Quantum Leap Decentralized Association',
  legalEntityType: 'dao',
  jurisdiction: 'CH',
  verificationStatus: 'unverified',
  complianceTier: 'tier1_standard',
  isVerified: false,
  branding: {
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop',
    tagline: 'Empowering open-source consensus researchers.',
    bio: 'Community-governed research DAO backing open quantum cryptography papers.',
    primaryColor: '#0ea5e9',
    socialLinks: {
      twitter: 'https://twitter.com/quantumleapdao',
      discord: 'https://discord.gg/quantumleap',
    },
  },
  publicEmail: 'grants@quantumleapdao.xyz',
  privateContacts: {
    billingContact: {
      name: 'Alexandre Meyer',
      email: 'alex@quantumleapdao.xyz',
      phone: '+41 22 767 61 11',
    },
  },
  complianceDocuments: [],
};

export const mockPendingSponsorOrg: SponsorOrganization = {
  id: 'sponsor-apex-fund',
  name: 'Apex Research Initiative',
  slug: 'apex-research',
  contactEmail: 'admissions@apexfund.org',
  website: 'https://apexfund.org',
  createdAt: '2026-08-15T09:00:00.000Z',
  tenantId: 'tenant-apex-global',
  ownerId: 'user-dr-clara',
  legalName: 'Apex Research Charitable Trust',
  legalEntityType: 'foundation',
  jurisdiction: 'GB',
  verificationStatus: 'pending',
  complianceTier: 'tier2_enhanced',
  isVerified: false,
  verificationNotes: 'Charity Commission UK registration review in progress.',
  branding: {
    primaryColor: '#10b981',
    tagline: 'Supporting frontier post-graduate scholarship recipients in the UK and EU.',
    publicEmail: 'contact@apexfund.org',
  },
  publicEmail: 'contact@apexfund.org',
  privateContacts: {
    billingContact: {
      name: 'Dr. Clara Oswald',
      email: 'clara.oswald@apexfund.org',
      billingAddress: '10 Downing St, London, UK',
    },
    taxId: 'GB-CHARITY-1189283',
  },
  complianceDocuments: [
    {
      id: 'doc-apex-charity',
      sponsorId: 'sponsor-apex-fund',
      type: 'certificate_of_incorporation',
      title: 'UK Charity Commission Certificate',
      fileName: 'charity_commission_cert.pdf',
      fileSizeBytes: 1200000,
      mimeType: 'application/pdf',
      uploadedAt: '2026-08-16T10:00:00.000Z',
      uploadedBy: 'user-dr-clara',
      status: 'pending_review',
    },
  ],
};

export const mockPublicSponsorProfile: PublicSponsorProfile = {
  id: 'sponsor-stellar-impact',
  name: 'Stellar Impact Foundation',
  slug: 'stellar-impact',
  legalEntityType: 'foundation',
  jurisdiction: 'US',
  verificationStatus: 'verified',
  complianceTier: 'tier2_enhanced',
  isVerified: true,
  verifiedAt: '2026-01-10T14:00:00.000Z',
  branding: {
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1200&auto=format&fit=crop',
    primaryColor: '#4f46e5',
    tagline: 'Catalyzing next-generation blockchain researchers and developers worldwide.',
    bio: 'The Stellar Impact Foundation distributes merit-based bursaries and developer grants to exceptional students.',
    website: 'https://stellarimpact.org',
    socialLinks: {
      twitter: 'https://twitter.com/stellarimpact',
      github: 'https://github.com/stellarimpact',
    },
  },
  publicEmail: 'public-grants@stellarimpact.org',
  publicWebsite: 'https://stellarimpact.org',
  publicPhone: '+1 (555) 234-5678',
  createdAt: '2026-01-01T00:00:00.000Z',
  programsCount: 3,
};

export const mockVerificationAuditEvents: SponsorVerificationAuditEvent[] = [
  {
    id: 'audit-ver-1',
    sequence: 1,
    sponsorId: 'sponsor-stellar-impact',
    tenantId: 'tenant-stellar-global',
    actorId: 'user-elena-owner',
    actorEmail: 'elena.rostova@stellarimpact.org',
    actorRole: 'owner',
    action: 'profile.created',
    newStatus: 'unverified',
    occurredAt: '2026-01-01T00:00:00.000Z',
    metadata: {
      legalEntityType: 'foundation',
      jurisdiction: 'US',
    },
  },
  {
    id: 'audit-ver-2',
    sequence: 2,
    sponsorId: 'sponsor-stellar-impact',
    tenantId: 'tenant-stellar-global',
    actorId: 'user-elena-owner',
    actorEmail: 'elena.rostova@stellarimpact.org',
    actorRole: 'owner',
    action: 'verification.document_uploaded',
    documentId: 'doc-stellar-incorp',
    occurredAt: '2026-01-05T10:00:00.000Z',
    metadata: {
      title: 'Delaware Certificate of Incorporation',
    },
  },
  {
    id: 'audit-ver-3',
    sequence: 3,
    sponsorId: 'sponsor-stellar-impact',
    tenantId: 'tenant-stellar-global',
    actorId: 'user-elena-owner',
    actorEmail: 'elena.rostova@stellarimpact.org',
    actorRole: 'owner',
    action: 'verification.requested',
    previousStatus: 'unverified',
    newStatus: 'pending',
    reason: 'Initial onboarding submission for Web3 STEM scholarship series.',
    occurredAt: '2026-01-05T11:00:00.000Z',
  },
  {
    id: 'audit-ver-4',
    sequence: 4,
    sponsorId: 'sponsor-stellar-impact',
    tenantId: 'tenant-stellar-global',
    actorId: 'auditor-chainverse-compliance',
    actorEmail: 'compliance@chainverse.org',
    actorRole: 'administrator',
    action: 'verification.approved',
    previousStatus: 'pending',
    newStatus: 'verified',
    previousTier: 'tier1_standard',
    newTier: 'tier2_enhanced',
    reason: 'Verified 501(c)(3) tax exemption and Delaware registration status.',
    occurredAt: '2026-01-10T14:00:00.000Z',
  },
];

